name: Website build and deploy

on:
  release:
    # types: [created]
  workflow_dispatch:
jobs:
  # 打包及上传Artifact
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 将代码拉到虚拟机
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Use Node.js # 安装Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install and Build # 下载依赖 打包项目
        run: |
          npm install
          npm run build
          npm run build:component
      - name: Upload artifact web
        uses: actions/upload-artifact@v3
        with:
          name: innixi-web
          path: ./build
      - name: Upload artifact component
        uses: actions/upload-artifact@v3
        with:
          name: innixi-web-es
          path: ./es
